# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.19

CMakeFiles/PS_MurderHouse.dir/Game.cpp.obj: ../Game.cpp
CMakeFiles/PS_MurderHouse.dir/Game.cpp.obj: ../Game.h

CMakeFiles/PS_MurderHouse.dir/main.cpp.obj: ../Game.h
CMakeFiles/PS_MurderHouse.dir/main.cpp.obj: ../main.cpp

